---
name: conventional-title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  run:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@a0b851005a0f82ac983a56ead5a8111c0d8e044a
        with:
          preset: conventional-changelog-angular@^5.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
